fire.env.local=true

# runtime control REST (optional)
flare.runtime.rest.enable=false
flare.runtime.rest.host=0.0.0.0
flare.runtime.rest.port=0
flare.runtime.rest.token=

# runtime schedule (optional)
flare.runtime.schedule.enable=true
flare.runtime.schedule.pool.size=1
