package com.bhcode.flare.flink.util;

import com.bhcode.flare.common.util.PropUtils;
import com.bhcode.flare.flink.conf.FlareFlinkConf;
import lombok.extern.slf4j.Slf4j;
import org.apache.flink.api.common.ExecutionConfig;
import org.apache.flink.runtime.util.EnvironmentInformation;
import org.apache.flink.streaming.api.datastream.DataStream;

import java.lang.reflect.Method;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Optional;

@Slf4j
public class FlinkUtils {

    private FlinkUtils() {
        // Private constructor to prevent instantiation
    }

    /**
     * SQL语法校验，如果语法错误，则返回错误堆栈
     *
     * @param sql SQL语句
     * @return 校验结果，成功返回空，失败返回异常
     */
    public static Optional<Exception> sqlValidate(String sql) {
        if (sql == null || sql.trim().isEmpty()) {
            return Optional.of(new IllegalArgumentException("SQL语句不能为空"));
        }
        
        try {
            // TODO: 使用 Flink 的 SQL 解析器进行校验
            // 可以使用 Calcite 解析器或 Flink 的 Table API 进行校验
            // 目前先做简单的语法检查
            String upperSql = sql.toUpperCase().trim();
            if (!upperSql.startsWith("SELECT") && !upperSql.startsWith("INSERT")
                    && !upperSql.startsWith("CREATE") && !upperSql.startsWith("DROP")
                    && !upperSql.startsWith("ALTER") && !upperSql.startsWith("SHOW")
                    && !upperSql.startsWith("DESC") && !upperSql.startsWith("EXPLAIN")
                    && !upperSql.startsWith("SET") && !upperSql.startsWith("USE")
                    && !upperSql.startsWith("WITH")) {
                return Optional.of(new IllegalArgumentException("不是有效的SQL语句"));
            }
            return Optional.empty();
        } catch (Exception e) {
            log.error("SQL语法校验失败: {}", sql, e);
            return Optional.of(e);
        }
    }

    /**
     * SQL语法校验
     *
     * @param sql SQL语句
     * @return true：校验成功 false：校验失败
     */
    public static boolean sqlLegal(String sql) {
        return sqlValidate(sql).isEmpty();
    }

    /**
     * 解析并设置配置文件中的配置信息到 ExecutionConfig
     *
     * @param config ExecutionConfig 实例
     */
    public static void parseConf(ExecutionConfig config) {
        if (config == null) {
            throw new IllegalArgumentException("Flink配置实例不能为空");
        }

        if (FlareFlinkConf.isAutoGenerateUidEnable()) {
            config.enableAutoGeneratedUIDs();
        } else {
            config.disableAutoGeneratedUIDs();
        }

        if (!FlareFlinkConf.isAutoTypeRegistrationEnable()) {
            config.disableAutoTypeRegistration();
        }

        if (FlareFlinkConf.isForceAvroEnable()) {
            config.enableForceAvro();
        } else {
            config.disableForceAvro();
        }

        if (FlareFlinkConf.isForceKryoEnable()) {
            config.enableForceKryo();
        } else {
            config.disableForceKryo();
        }

        if (FlareFlinkConf.isGenericTypesEnable()) {
            config.enableGenericTypes();
        } else {
            config.disableGenericTypes();
        }

        if (FlareFlinkConf.isObjectReuseEnable()) {
            config.enableObjectReuse();
        } else {
            config.disableObjectReuse();
        }

        if (FlareFlinkConf.getAutoWatermarkInterval() != -1) {
            config.setAutoWatermarkInterval(FlareFlinkConf.getAutoWatermarkInterval());
        }

        if (FlareFlinkConf.getClosureCleanerLevel() != null && !FlareFlinkConf.getClosureCleanerLevel().isEmpty()) {
            try {
                ExecutionConfig.ClosureCleanerLevel level =
                        ExecutionConfig.ClosureCleanerLevel.valueOf(FlareFlinkConf.getClosureCleanerLevel().toUpperCase());
                config.setClosureCleanerLevel(level);
            } catch (Exception e) {
                log.warn("Invalid closure cleaner level: {}", FlareFlinkConf.getClosureCleanerLevel());
            }
        }

        if (FlareFlinkConf.getDefaultInputDependencyConstraint() != null
                && !FlareFlinkConf.getDefaultInputDependencyConstraint().isEmpty()) {
            try {
                callInputDependencyConstraintSetter(config, FlareFlinkConf.getDefaultInputDependencyConstraint());
            } catch (Exception e) {
                log.warn("Invalid input dependency constraint: {}", FlareFlinkConf.getDefaultInputDependencyConstraint());
            }
        }

        if (FlareFlinkConf.getExecutionMode() != null && !FlareFlinkConf.getExecutionMode().isEmpty()) {
            callExecutionModeSetter(config, FlareFlinkConf.getExecutionMode());
        }

        if (FlareFlinkConf.getLatencyTrackingInterval() != -1) {
            config.setLatencyTrackingInterval(FlareFlinkConf.getLatencyTrackingInterval());
        }

        if (FlareFlinkConf.getMaxParallelism() != -1) {
            config.setMaxParallelism(FlareFlinkConf.getMaxParallelism());
        }

        if (FlareFlinkConf.getTaskCancellationInterval() != -1) {
            config.setTaskCancellationInterval(FlareFlinkConf.getTaskCancellationInterval());
        }

        if (FlareFlinkConf.getTaskCancellationTimeoutMillis() != -1) {
            config.setTaskCancellationTimeout(FlareFlinkConf.getTaskCancellationTimeoutMillis());
        }

        config.setUseSnapshotCompression(FlareFlinkConf.isUseSnapshotCompression());
    }

    /**
     * 获取 JobManager 或 TaskManager 的标识
     *
     * @return JobManager/container_xxx_xxx_xx_xxxx
     */
    public static String getResourceId() {
        if (isJobManager()) {
            return "JobManager";
        }
        return PropUtils.getString("taskmanager.resource-id", getHostName());
    }

    /**
     * 获取 applicationId
     *
     * @return applicationId
     */
    public static String getApplicationId() {
        return PropUtils.getString("high-availability.cluster-id");
    }

    /**
     * 获取 Flink 版本号
     *
     * @return Flink 版本号
     */
    public static String getVersion() {
        try {
            return EnvironmentInformation.getVersion();
        } catch (Exception e) {
            log.warn("获取 Flink 版本号失败", e);
            return "unknown";
        }
    }

    /**
     * 判断当前环境是否为 JobManager
     *
     * @return true: JobManager, false: TaskManager
     */
    public static boolean isJobManager() {
        try {
            Method method = EnvironmentInformation.class.getDeclaredMethod("isJobManager");
            Object ret = method.invoke(null);
            return Boolean.parseBoolean(String.valueOf(ret));
        } catch (Exception e) {
            log.debug("EnvironmentInformation.isJobManager not available, default to true");
            return true;
        }
    }

    /**
     * 判断当前环境是否为 TaskManager
     *
     * @return true: TaskManager, false: JobManager
     */
    public static boolean isTaskManager() {
        return !isJobManager();
    }

    /**
     * 判断当前运行模式是否为 yarn-application 模式
     *
     * @return true: yarn-application 模式
     */
    public static boolean isYarnApplicationMode() {
        return "yarn-application".equalsIgnoreCase(getDeployMode());
    }

    /**
     * 判断当前运行模式是否为 yarn-per-job 模式
     *
     * @return true: yarn-per-job 模式
     */
    public static boolean isYarnPerJobMode() {
        return "yarn-per-job".equalsIgnoreCase(getDeployMode());
    }

    /**
     * 获取 Flink 的运行模式
     *
     * @return 运行模式（local, yarn-per-job, yarn-application 等）
     */
    public static String getDeployMode() {
        String fromConfig = resolveDeployModeFromConfig();
        if (!fromConfig.isEmpty()) {
            return fromConfig;
        }
        try {
            Class<?> globalConf = Class.forName("org.apache.flink.configuration.GlobalConfiguration");
            Method method = globalConf.getMethod("getRunMode");
            Object ret = method.invoke(null);
            String mode = ret == null ? "" : String.valueOf(ret);
            return normalizeDeployMode(mode);
        } catch (Exception e) {
            return "local";
        }
    }

    /**
     * 用于判断引擎是否已完成上下文的初始化
     *
     * @return true: 已初始化, false: 未初始化
     */
    public static boolean isEngineUp() {
        FlinkSingletonFactory factory = FlinkSingletonFactory.getInstance();
        return factory.getStreamEnv() != null || factory.getTableEnv() != null;
    }

    /**
     * 用于判断引擎是否已销毁上下文
     *
     * @return true: 已销毁, false: 未销毁
     */
    public static boolean isEngineDown() {
        FlinkSingletonFactory factory = FlinkSingletonFactory.getInstance();
        return factory.getStreamEnv() == null && factory.getTableEnv() == null;
    }

    /**
     * 为算子设置 UID 和 Name
     */
    public static <T> DataStream<T> uname(
            DataStream<T> stream, String uid, String name) {
        if (stream != null) {
            if (uid != null && !uid.trim().isEmpty()) {
                stream.uid(uid.trim());
            }
            if (name != null && !name.trim().isEmpty()) {
                stream.name(name.trim());
            } else if (uid != null && !uid.trim().isEmpty()) {
                stream.name(uid.trim());
            }
        }
        return stream;
    }

    private static void callExecutionModeSetter(ExecutionConfig config, String mode) {
        try {
            Class<?> executionMode = Class.forName("org.apache.flink.api.common.ExecutionMode");
            Method valueOf = executionMode.getMethod("valueOf", String.class);
            Object enumValue = valueOf.invoke(null, mode.trim().toUpperCase());
            Method setter = ExecutionConfig.class.getMethod("setExecutionMode", executionMode);
            setter.invoke(config, enumValue);
        } catch (Exception e) {
            log.debug("ExecutionMode not supported in this Flink version: {}", mode);
        }
    }

    private static void callInputDependencyConstraintSetter(ExecutionConfig config, String constraint) {
        try {
            Class<?> constraintClass = Class.forName("org.apache.flink.api.common.InputDependencyConstraint");
            Method valueOf = constraintClass.getMethod("valueOf", String.class);
            Object enumValue = valueOf.invoke(null, constraint.trim().toUpperCase());
            Method setter = ExecutionConfig.class.getMethod("setDefaultInputDependencyConstraint", constraintClass);
            setter.invoke(config, enumValue);
        } catch (Exception e) {
            log.debug("InputDependencyConstraint not supported in this Flink version: {}", constraint);
        }
    }

    private static String getHostName() {
        try {
            return InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException e) {
            return "TaskManager";
        }
    }

    private static String resolveDeployModeFromConfig() {
        String[] keys = new String[] {
                "execution.target",
                "flink.execution.target",
                "deployment.target",
                "flink.deployment.target"
        };
        for (String key : keys) {
            String value = PropUtils.getString(key, "");
            String normalized = normalizeDeployMode(value);
            if (!normalized.isEmpty()) {
                return normalized;
            }
        }
        return "";
    }

    private static String normalizeDeployMode(String mode) {
        if (mode == null) {
            return "local";
        }
        String trimmed = mode.trim();
        if (trimmed.isEmpty() || "null".equalsIgnoreCase(trimmed)) {
            return "local";
        }
        return trimmed;
    }
}
